# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import general.models
import media_server.models
import media_server.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent_id', models.CharField(max_length=22)),
                ('status', models.IntegerField(choices=[(0, 'not converted'), (1, 'in progress'), (2, 'converted'), (3, 'error')], default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path)),
                ('id', general.models.ShortUUIDField(prefix='a', primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent_id', models.CharField(max_length=22)),
                ('status', models.IntegerField(choices=[(0, 'not converted'), (1, 'in progress'), (2, 'converted'), (3, 'error')], default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path)),
                ('id', general.models.ShortUUIDField(prefix='d', primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent_id', models.CharField(max_length=22)),
                ('status', models.IntegerField(choices=[(0, 'not converted'), (1, 'in progress'), (2, 'converted'), (3, 'error')], default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('id', general.models.ShortUUIDField(prefix='i', primary_key=True, serialize=False)),
                ('file', models.ImageField(storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent_id', models.CharField(max_length=22)),
                ('status', models.IntegerField(choices=[(0, 'not converted'), (1, 'in progress'), (2, 'converted'), (3, 'error')], default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path)),
                ('id', general.models.ShortUUIDField(prefix='x', primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent_id', models.CharField(max_length=22)),
                ('status', models.IntegerField(choices=[(0, 'not converted'), (1, 'in progress'), (2, 'converted'), (3, 'error')], default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path)),
                ('id', general.models.ShortUUIDField(prefix='v', primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
