# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0002_auto_20190130_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='document',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='image',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='other',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='video',
            name='metadata',
        ),
        migrations.AddField(
            model_name='audio',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='document',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='image',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='other',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='video',
            name='exif',
            field=models.TextField(),
        ),
    ]
