# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0003_auto_20190201_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='parent_id',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='parent_id',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='parent_id',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='parent_id',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='parent_id',
            new_name='entity_id',
        ),
    ]
