# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0004_auto_20190205_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='other',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
