# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 12:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.encoder
import media_server.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0006_auto_20190313_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='exif',
            field=media_server.fields.ExifField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, editable=False, load_kwargs={}),
        ),
        migrations.AlterField(
            model_name='document',
            name='exif',
            field=media_server.fields.ExifField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, editable=False, load_kwargs={}),
        ),
        migrations.AlterField(
            model_name='image',
            name='exif',
            field=media_server.fields.ExifField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, editable=False, load_kwargs={}),
        ),
        migrations.AlterField(
            model_name='other',
            name='exif',
            field=media_server.fields.ExifField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, editable=False, load_kwargs={}),
        ),
        migrations.AlterField(
            model_name='video',
            name='exif',
            field=media_server.fields.ExifField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, editable=False, load_kwargs={}),
        ),
    ]
