# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0006_auto_20190313_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='other',
            name='exif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='exif',
            field=models.TextField(),
        ),
    ]
