# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0007_auto_20190320_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='license',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='license',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='license',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='license',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='license',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
