# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0008_auto_20190409_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='license',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='license',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='license',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='license',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='license',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
