# Generated by Django 2.2.2 on 2019-06-25 08:12

from django.db import migrations, models
import media_server.models
import media_server.storages


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0011_auto_20190605_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path),
        ),
    ]
