# Generated by Django 2.2.2 on 2019-06-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0013_auto_20190625_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='exif',
            field=models.TextField(),
        ),
    ]
