# Generated by Django 2.2.2 on 2019-06-25 15:37

from django.db import migrations
import jsonfield.encoder
import media_server.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0013_auto_20190625_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='exif',
            field=media_server.fields.ExifField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, editable=False, load_kwargs={}),
        ),
    ]
