# Generated by Django 2.2.11 on 2020-05-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0015_auto_20191211_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created']},
        ),
    ]
