# Generated by Django 2.2.21 on 2021-07-21 14:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import media_server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0016_auto_20200519_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='license',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'label': {'de': 'urheberrechtlich geschützt', 'en': 'Copyright'}, 'source': 'http://base.uni-ak.ac.at/portfolio/licenses/copyright'}, validators=[media_server.validators.validate_license]),
            preserve_default=False,
        ),
    ]
