# Generated by Django 2.2.19 on 2021-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('media_server', '0017_auto_20210126_0907'), ('media_server', '0018_media_archive_status'), ('media_server', '0019_remove_media_archive_status'), ('media_server', '0020_media_archive_status'), ('media_server', '0021_remove_media_archive_status'), ('media_server', '0022_media_archive_status'), ('media_server', '0023_auto_20210505_1444')]

    dependencies = [
        ('media_server', '0016_auto_20200519_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='archive_status',
            field=models.IntegerField(choices=[(0, 'not archived'), (1, 'to be archived'), (2, 'archival in progress'), (3, 'archived'), (4, 'error')], default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='archive_URI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='archive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
