# Generated by Django 2.2.21 on 2021-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0017_auto_20210721_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='archive_URI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='archive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='archive_status',
            field=models.IntegerField(choices=[(0, 'not archived'), (1, 'to be archived'), (2, 'archival in progress'), (3, 'archived'), (4, 'error')], default=0),
        ),
    ]
