# Generated by Django 2.2.21 on 2021-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0017_auto_20210721_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', '-created']},
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.PositiveIntegerField(default=2147483647),
        ),
    ]
