# Generated by Django 2.2.16 on 2021-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0017_auto_20210126_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='archive_status',
            field=models.IntegerField(choices=[(0, 'not archived'), (1, 'in progress'), (2, 'archived'), (3, 'error')], default=0),
        ),
    ]
