# Generated by Django 2.2.21 on 2022-03-16 16:25

from django.db import migrations, models
import media_server.models
import media_server.storages


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0017_auto_20210721_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(max_length=255, storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path),
        ),
    ]
