    # Generated by Django 2.2.21 on 2021-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0018_auto_20210902_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='archive_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='archive_status',
            field=models.IntegerField(choices=[(0, 'not archived'), (1, 'to be archived'), (2, 'archival in progress'), (3, 'archived'), (4, 'error'), (5, 'archival update in queue')], default=0),
        ),
    ]
