# Generated by Django 2.2.21 on 2021-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0019_auto_20210913_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
