# Generated by Django 2.2.21 on 2021-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0020_auto_20220316_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
