# Generated by Django 2.2.28 on 2022-10-21 10:15

from django.db import migrations, models
import media_server.clamav
import media_server.models
import media_server.storages


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0021_media_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(max_length=255, storage=media_server.storages.ProtectedFileSystemStorage(), upload_to=media_server.models.user_directory_path, validators=[media_server.clamav.validate_file_infection]),
        ),
    ]
