# Generated by Django 2.2.16 on 2021-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0022_media_archive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='archive_URI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='archive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
