# Generated by Django 3.2.20 on 2023-08-22 16:54

from django.db import migrations, models
import media_server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('media_server', '0022_auto_20221021_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='exif',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='media',
            name='license',
            field=models.JSONField(validators=[media_server.validators.validate_license]),
        ),
    ]
