# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='title',
            field=models.CharField(default='Untitled Entity', max_length=255),
            preserve_default=False,
        ),
    ]
