# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 15:55
from __future__ import unicode_literals

import core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190207_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='text',
        ),
        migrations.AddField(
            model_name='entity',
            name='texts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[core.validators.validate_texts], verbose_name='text'),
        ),
    ]
