# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 14:35
from __future__ import unicode_literals

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190207_1712'),
    ]

    operations = [
        TrigramExtension(),
    ]
