# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190221_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
