# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 14:29
from __future__ import unicode_literals

import core.validators
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20190228_1656'),
    ]

    operations = [
        migrations.RenameModel('Entity', 'Entry'),
        migrations.RenameField('Relation', 'from_entity', 'from_entry'),
        migrations.RenameField('Relation', 'to_entity', 'to_entry'),
        migrations.AlterField(
            model_name='relation',
            name='from_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entries', to='core.Entry'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entries', to='core.Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('from_entry', 'to_entry')]),
        ),
    ]
