# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 09:58
from __future__ import unicode_literals

import core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190409_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
