# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 10:01
from __future__ import unicode_literals

import core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190604_1158'),
    ]

    operations = [
        migrations.RunSQL([
            'UPDATE core_entry SET "type" = concat(\'{"source":"\', "type", \'"}\') WHERE "type" IS NOT NULL AND "type" != \'\''
        ]),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[core.validators.validate_type], verbose_name='type'),
        ),
    ]
