# Generated by Django 2.2.21 on 2021-09-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190806_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='archive_URI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='archive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
