# Generated by Django 2.2.16 on 2021-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190806_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='archive_URI',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='archive_id',
            field=models.CharField(default='', max_length=22),
        ),
    ]
