# Generated by Django 2.2.19 on 2021-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0017_auto_20210123_1711'), ('core', '0018_auto_20210123_1738'), ('core', '0019_auto_20210505_1444')]

    dependencies = [
        ('core', '0016_auto_20190806_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='archive_URI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='archive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
