# Generated by Django 2.2.28 on 2022-04-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_entry_new_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='showroom_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
