# Generated by Django 2.2.21 on 2021-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210902_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='archive_date',
            field=models.DateTimeField(null=True),
        ),
    ]
