# Generated by Django 2.2.16 on 2021-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210123_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='archive_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
