# Generated by Django 2.2.16 on 2021-05-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210123_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='archive_URI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='archive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
