# Generated by Django 2.2.21 on 2021-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_entry_archive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
