# Generated by Django 3.2.20 on 2023-08-22 16:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20221121_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='entry',
            name='keywords',
            field=models.JSONField(blank=True, null=True, validators=[core.validators.validate_keywords], verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='texts',
            field=models.JSONField(blank=True, null=True, validators=[core.validators.validate_texts], verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.JSONField(blank=True, null=True, validators=[core.validators.validate_type], verbose_name='type'),
        ),
    ]
