STATUS_NOT_ARCHIVED = 0
STATUS_TO_BE_ARCHIVED = 1
STATUS_ARCHIVE_IN_PROGRESS = 2
STATUS_ARCHIVED = 3
STATUS_ARCHIVE_ERROR = 4
STATUS_ARCHIVE_IN_UPDATE = 5
ARCHIVE_STATUS_CHOICES = (
    (STATUS_NOT_ARCHIVED, 'not archived'),
    (STATUS_TO_BE_ARCHIVED, 'to be archived'),
    (STATUS_ARCHIVE_IN_PROGRESS, 'archival in progress'),
    (STATUS_ARCHIVED, 'archived'),
    (STATUS_ARCHIVE_ERROR, 'error'),
    (STATUS_ARCHIVE_IN_UPDATE, 'archival update in queue'),
)
